# Generated by Django 3.2.13 on 2022-12-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221216_1026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
