# Generated by Django 3.2.16 on 2022-12-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=255)),
                ('addres_street', models.CharField(max_length=255)),
                ('address_city', models.CharField(max_length=255)),
                ('address_zipcode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=20)),
                ('expiration_date', models.DateField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='student_photos')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
