# Generated by Django 3.2.16 on 2022-12-30 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_studentcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcard',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='card', to='accounts.student'),
        ),
    ]
