# Generated by Django 3.2.16 on 2023-01-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_department_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='addres_street',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address_zipcode',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
    ]
