# Generated by Django 3.2.16 on 2023-02-05 12:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230205_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='student',
            name='addres_street',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address_zipcode',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='StudentCourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Data zapisania studenta')),
                ('final_grade', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Ocena końcowa')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
