# Generated by Django 3.2.16 on 2023-02-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20230205_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='accounts.StudentCourseMembership', to='accounts.Student'),
        ),
    ]
