# Generated by Django 3.2.16 on 2023-02-09 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcoursemembership',
            name='final_grade',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Ocena końcowa'),
        ),
    ]
