# Generated by Django 3.2.16 on 2023-02-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_studentcoursemembership_final_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='choice_value',
            field=models.CharField(choices=[(1, 'text'), (2, 'drugi text')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
