# Generated by Django 3.2.16 on 2023-02-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_course_choice_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='choice_value',
        ),
    ]
